version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install.sh configure-profile.sh applyterraform.sh # make files executable
      - ./install.sh # install terraform
      - ./configure-profile.sh # configure named profile

  build:
    commands:
      - ./applyterraform.sh